name: {{APP_PACKAGE_NAME}}
description: {{APP_DESCRIPTION}}
publish_to: 'none'
version: {{APP_VERSION}}+{{APP_BUILD_NUMBER}}

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.16.3
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.0
  permission_handler: ^11.3.1
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
